import = [ "~/.config/alacritty/dracula.toml" ]

[window]
padding = { x = 4, y = 4 }
decorations = "None"
dynamic_padding = true
dynamic_title = false
startup_mode = "Maximized"
decorations_theme_variant = "Light"
opacity = 0.5
option_as_alt = "Both"

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
italic = { family = "Hack Nerd Font", style = "Italic" }
bold = { family = "Hack Nerd Font", style = "Bold" }
size = 15.0

